[package]
name = "quine-mccluskey"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
itertools = "0.12.1"
rand = "0.8.5"

[dependencies]
serde = { version = "1.0.197", features = ["derive"], optional = true }
thiserror = "1.0.57"
